# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b75f8d34bd2993b3465792d3710701875d8b72151bd3baffa7df904f10786f29c11350b460ddf7725a684e22ed192af0de648e63431a55cef662fce15e43f17

test:
  secret_key_base: 14147213bc740d218b02a92e67e98068d14cfecf89b63e7a67a81869819f55e8dbf7311b589a6d220a2a551f455c06d515d55f3ab6c11f96e53aece0919949d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
